### ISSUE TITLE
Infinite buildElementProperties recursion detected

### ISSUE THREAD

**Issue by dvc** [strongloop/loopback-soap#10]
If wsdl has complex data tree with reusable models, same models a parsed more than once time. Code generation fails due to recursion deep overflow.

Problem in function: 
lib/codegen/generator-soap.js::buildElementProperties

**Comment by dvc** [comment]
Sorry, autotests fails. PR is invalid.

**Comment by xjkul** [comment]
PR is valid in case wsdl is complex, here is a simle patch:

= // builds properties for input/output params. It recursively builds properties for elements defined in = the schema
= function buildElementProperties(models, modelName, propertyList, outerElem, schemaTypes) {
  
 + if (models[modelName]) {
 +   return models;
 + }

**Comment by dhmlau** [comment]
Closing as done.
